### ISSUE TITLE
kernel is running but I am unable to download data

### ISSUE THREAD

**Issue by Hmishra1** [fmagrini/seislib#8] opened 2023-04-13 18:53 UTC
''

COLLECTING STATIONS INFO***

Inventory created at 2023-04-13T14:46:15.343300Z
	Created by: IRIS WEB SERVICE: fdsnws-station | version: 1.1.52
		    http://service.iris.edu/fdsnws/station/1/query?channel=LH%2A%2CBH%2...
	Sending institution: IRIS-DMC (IRIS-DMC)
	Contains:
		Networks (4):
			NK, XF, XQ, YL
		Stations (132):
			NK.KKN (Kakani, Nepal)
			XF.H0010 (H0010)
			XF.H0020 (H0020)
			XF.H0030 (H0030)
			XF.H0040 (H0040)
			XF.H0050 (H0050)
			XF.H0060 (H0060)
			XF.H0070 (H0070)
			XF.H0080 (H0080)
			XF.H0090 (H0090)
			XF.H0100 (H0100)
			XF.H0120 (H0120)
			XF.H0130 (H0130)
			XF.H0150 (H0150)
			XF.H0160 (H0160)
			XF.H0170 (H0170)
			XF.H0180 (H0180)
			XF.H0190 (H0190)
			XF.H0200 (H0200)
			XF.H0210 (H0210)
			XF.H0220 (H0220)
			XF.H0230 (H0230)
			XF.H0240 (H0240)
			XF.H0250 (H0250)
			XF.H0260 (H0260)
			XF.H0270 (H0270)
			XF.H0280 (H0280)
			XF.H0290 (H0290)
			XF.H0310 (H0310)
			XF.H0320 (H0320)
			XF.H0330 (H0330)
			XF.H0340 (H0340)
			XF.H0350 (H0350)
			XF.H0360 (H0360)
			XF.H0370 (H0370)
			XF.H0380 (H0380)
			XF.H0390 (H0390)
			XF.H0400 (H0400)
			XF.H0410 (H0410)
			XF.H0420 (H0420)
			XF.H0430 (H0430)
			XF.H0440 (H0440)
			XF.H0450 (H0450)
			XF.H0460 (H0460)
			XF.H0470 (H0470)
			XF.H0480 (H0480)
			XF.H0490 (H0490)
			XF.H0500 (H0500)
			XF.H0510 (H0510)
			XF.H0520 (H0520)
			XF.H0530 (H0530)
			XF.H0540 (H0540)
			XF.H0550 (H0550)
			XF.H0560 (H0560)
			XF.H0570 (H0570)
			XF.H0580 (H0580)
			XF.H0590 (H0590)
			XF.H0600 (H0600)
			XF.H0610 (H0610)
			XF.H0620 (H0620)
			XF.H0630 (H0630)
			XF.H0640 (H0640)
			XF.H0641 (H0641)
			XF.H0650 (H0650)
			XF.H0655 (H0655)
			XF.H0660 (H0660)
			XF.H0670 (H0670)
			XF.H0680 (H0680)
			XF.H0690 (H0690)
			XF.H0700 (H0700)
			XF.H0710 (H0710)
			XF.H0720 (H0720)
			XF.H0730 (H0730)
			XF.H0740 (H0740)
			XF.H0750 (H0750)
			XF.H0760 (H0760)
			XF.H0770 (H0770)
			XF.H0780 (H0780)
			XF.H0790 (H0790)
			XF.H0800 (H0800)
			XF.H0810 (H0810)
			XF.NBENS (NBENS)
			XF.NDOML (NDOML)
			XF.NG010 (NG010)
			XF.NG020 (NG020)
			XF.NG030 (NG030)
			XF.NG040 (NG040)
			XF.NG050 (NG050)
			XF.NG060 (NG060)
			XF.NGUMB (NGUMB)
			XF.NKDMG (NKDMG)
			XF.NP010 (NP010)
			XF.NP020 (NP020)
			XF.NP030 (NP030)
			XF.NP035 (NP035)
			XF.NP040 (NP040)
			XF.NP050 (NP050)
			XF.NP060 (NP060)
			XF.NP070 (NP070)
			XF.NP071 (NP071)
			XF.NP075 (NP075)
			XF.NP080 (NP080)
			XF.NP082 (NP082)
			XF.NP085 (NP085)
			XF.NP090 (NP090)
			XF.NP100 (NP100)
			XF.NTHAK (NTHAK)
			XQ.NA010 (Katmandu,Nepal)
			XQ.NA020 (Katmandu,Nepal)
			XQ.NA030 (Katmandu,Nepal)
			XQ.NA040 (Katmandu,Nepal)
			XQ.NA050 (Katmandu,Nepal)
			XQ.NA070 (Katmandu,Nepal)
			XQ.NA080 (Katmandu,Nepal)
			XQ.NA090 (Katmandu,Nepal)
			XQ.NA100 (Katmandu,Nepal)
			XQ.NA110 (Katmandu,Nepal)
			XQ.NA150 (Katmandu,Nepal)
			XQ.NA160 (Katmandu,Nepal)
			XQ.NA170 (Katmandu,Nepal)
			XQ.NA180 (Katmandu,Nepal)
			XQ.NA250 (Katmandu,Nepal)
			XQ.NA270 (Katmandu,Nepal)
			XQ.NA330 (Katmandu,Nepal)
			XQ.NA340 (Katmandu,Nepal)
			XQ.NA360 (Katmandu,Nepal)
			XQ.NA390 (Katmandu,Nepal)
			XQ.NA400 (Katmandu,Nepal)
			XQ.NA410 (Katmandu,Nepal)
			YL.SAGA (-)
			YL.THAK (-)
			YL.XIXI (-)
		Channels (0):

''

data is not getting download , kernel is running

**Comment by fmagrini** [comment] 2023-04-13 23:10
Once again, please share your code. Otherwise I cannot reproduce your issue.

Based on your output, it seems one of your stations has no channels. This triggers an unexpected behaviour of `ANDownloader.get_inventory`.

If you could copy-paste your code here, I should be able to sort this thing out in a short time. Please also specify the version of seislib you are using.

**Comment by fmagrini** [comment] 2023-04-14 03:18
Unfortunately, I could not reproduce your issue. The following code will successfully download the station metadata (which you can access through `downloader.inventory`) related to the YL network:

    from obspy import UTCDateTime as UTC
    from seislib.an import ANDownloader


    stations_config = dict(network='YL',
                           channel='BH*,LH*',
                           starttime=UTC(2001, 10, 1),
                           endtime=UTC(2002, 3, 1),
                           includerestricted=False)

    downloader = ANDownloader(savedir='test', 
                              inventory_name='YL.xml',
                              provider='iris',
                              sampling_rate=1,
                              prefilter=(0.005, 0.01, 0.5, 1),
                              units='disp',
                              attach_response=False,
                              stations_config=stations_config,
                              verbose=True)

For the time being, I will close this issue. Feel free to reopen it, but eventually please share your Python code and seislib version.

**Closed** 2023-04-14 03:22 UTC
